# Generated by Django 5.2 on 2025-04-10 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('empId', models.CharField(max_length=10)),
                ('department', models.CharField(max_length=20)),
                ('designation', models.CharField(max_length=20)),
                ('salary', models.IntegerField()),
                ('joining_date', models.DateField()),
            ],
        ),
    ]
