# Generated by Django 5.2 on 2025-04-09 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_remove_datachangelog_model_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datachangelog',
            name='content_type',
            field=models.CharField(max_length=255),
        ),
    ]
