# Generated by Django 5.2 on 2025-04-09 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('logs', '0003_alter_datachangelog_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datachangelog',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
